network_params:
  input_channel: 1
  output_channel: 256
  hidden_size: 256
imgH: 64
lang_list:
         - 'ru'
character_list: 0123456789!"#$%&'()*+,-./:;<=>?@[\]№_`{|}~ €₽ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя
number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]№_`{|}~ €₽"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя'
#experiment_name: 'ru_gub_enis'
experiment_name: 'ru_filtered_3000k'
train_data: 'all_data'
valid_data: 'all_data/new_val'
manualSeed: 1111
workers: 12
batch_size: 200 #32
num_iter: 600000
valInterval: 1000
saved_model: 'saved_models\ru_filtered_1000k\best_accuracy.pth'
FT: True
optim: Adadelta # значение по умолчанию - Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'new_dataset' # это папка dataset в train_data
batch_ratio: '1'
total_data_usage_ratio: 1.0
batch_max_length: 68
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Архитектура модели
Transformation: 'None' #TPS
FeatureExtraction: 'ResNet' #ResNet, VGG
SequenceModeling: 'BiLSTM'
Prediction: 'Attn' #Prediction: = 'Attn', 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'beamsearch' # 'beamsearch'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False